### PR TITLE
alternate class plans for students new to computers

### PR DESCRIPTION
**Pull request by mwoguri**
- For younger students with limited computer experience. 
- Includes activities for learning concepts without coding and recipes that are partially completed. 
- Does not require students to have a github account--projects are small so teachers can just clone the repo each day.

Recipes added here: https://github.com/League-central/java-modules/pull/109

### CODE REVIEW

**Comment by mwoguri** [comment]
@codybsauer or @jaLeague, perhaps could you review?

**Comment by mwoguri** [comment]
@mjfre this goes with https://github.com/League-central/java-modules/pull/109.  Perhaps you could take a look at this too?

**Comment by dencee** [comment]
Session1Alternate.html line 69-70: remove 2nd bullet point under rocket. It's part of the previous sentence.
instead</li><li>ask students to... => instead ask students to...

**Comment by dencee** [comment]
I think the google document links should be added into the repo to keep everything version controlled.

**Pull request merged**
